- id: '1765295873034'
  alias: Velký úklid
  description: ''
  triggers:
  - trigger: time_pattern
    hours: '11'
    minutes: '00'
    seconds: '00'
  conditions:
  - condition: time
    weekday:
    - mon
    - wed
    - fri
  actions:
  - action: vacuum.send_command
    data:
      params:
      - service: vacuum.send_command
        data:
          command: app_segment_clean
          params:
          - segments:
            - 16
            - 18
            - 19
            - 20
            - 21
            - 22
        target:
          entity_id: vacuum.kyckoplasic
      command: app_segment_clean
    target:
      entity_id: vacuum.kyckoplasic
  mode: single
- id: '1765298501285'
  alias: Malý úklid
  description: ''
  triggers:
  - trigger: time_pattern
    hours: '11'
    minutes: '00'
    seconds: '00'
  conditions:
  - condition: time
    weekday:
    - tue
    - thu
    - sat
    - sun
  actions:
  - action: vacuum.send_command
    data:
      params:
      - service: vacuum.send_command
        data:
          command: app_segment_clean
          params:
          - segments:
            - 16
        target:
          entity_id: vacuum.kyckoplasic
      command: app_segment_clean
    target:
      entity_id: vacuum.kyckoplasic
  mode: single
- id: '1765304500598'
  alias: Bulb default
  description: ''
  triggers:
  - type: turned_on
    device_id: afaeb10ae433f552f30dc9d87f3a85eb
    entity_id: 43b502cfb3b2fafd1d60657bf4389c58
    domain: light
    trigger: device
  conditions: []
  actions:
  - action: yeelight.set_color_temp_scene
    metadata: {}
    data:
      kelvin: 5100
      brightness: 100
  mode: single
